version: '3.9'
# docker compose allow us to compose multiple containers and allow them talk to each other
# to run docker-compose up 
# docker exec -it containerId bash -l - run interactive shell 
# and run python code 
services:
    db:
        image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: yourpassword
          POSTGRES_DB: airline 

    web:
    # build from this directory
        build: .
        # run the ff command
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"

        depends_on:
          - db
