name: Testing 
on: push 
# the on means when should this workflow run we want it to run when anyone pushes to the repo

jobs:
  test_project:
    runs-on: ubuntu-latest
    # vm to run on
    steps:
    # specify what steps should happen when someone tries to test the prog
    # first checkout the code 
    # run django unit tests 
    # things to install 
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install --user django 
        python3 manage.py test
      working-directory: django/airline


